version: "3.7"
services:
  dockerize-api:
    image: sactio1811/dockerize
    build:
      context: .
    ports:
      - "29293:8080"
    networks:
      - kb-backend1
    command: ["./main"]

  curl-api:
    image: byrnedo/alpine-curl
    networks:
      - kb-backend1
    command: [ "dockerize-api:8080" ]
networks:
  kb-backend1:
    external: false
    name: kb-backend1